code --install-extension aaron-bond.better-comments
code --install-extension adpyke.codesnap
code --install-extension agutierrezr.emmet-keybindings
code --install-extension alefragnani.numbered-bookmarks
code --install-extension alexiv.vscode-angular2-files
code --install-extension almenon.arepl
code --install-extension batisteo.vscode-django
code --install-extension bierner.markdown-preview-github-styles
code --install-extension cliffordfajardo.highlight-line-vscode
code --install-extension d-koppenhagen.file-tree-to-text-generator
code --install-extension daiyy.quick-html-previewer
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension deerawan.vscode-dash
code --install-extension denoland.vscode-deno
code --install-extension donjayamanne.python-environment-manager
code --install-extension donjayamanne.python-extension-pack
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EQuimper.react-native-react-redux
code --install-extension esbenp.prettier-vscode
code --install-extension FallenMax.mithril-emmet
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension fractalbrew.backticks
code --install-extension frhtylcn.pythonsnippets
code --install-extension GitHub.codespaces
code --install-extension GitHub.github-vscode-theme
code --install-extension GitHub.vscode-pull-request-github
code --install-extension hbenl.vscode-test-explorer
code --install-extension Ionide.Ionide-fsharp
code --install-extension jasonlhy.hungry-delete
code --install-extension JerryHong.autofilename
code --install-extension johnpapa.Angular2
code --install-extension jundat95.react-native-snippet
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension liamhammett.inline-parameters
code --install-extension littlefoxteam.vscode-python-test-adapter
code --install-extension marabesi.php-import-checker
code --install-extension mathematic.vscode-pdf
code --install-extension Mikael.Angular-BeastCode
code --install-extension mongodb.mongodb-vscode
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.dotnet-interactive-vscode
code --install-extension ms-dotnettools.vscode-dotnet-pack
code --install-extension ms-edgedevtools.vscode-edge-devtools
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-ossdata.vscode-postgresql
code --install-extension ms-python.black-formatter
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.js-debug-nightly
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.vscode-react-native
code --install-extension njpwerner.autodocstring
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel5-snippets
code --install-extension PulkitGangwar.nextjs-snippets
code --install-extension rangav.vscode-thunder-client
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension ryannaddy.laravel-artisan
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension solidjs-community.solid-snippets
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension toba.vsfire
code --install-extension twxs.cmake
code --install-extension vincaslt.highlight-matching-tag
code --install-extension vinliao.fast-arrow
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-pack
code --install-extension vscode-icons-team.vscode-icons
code --install-extension WakaTime.vscode-wakatime
code --install-extension WallabyJs.quokka-vscode
code --install-extension wesbos.theme-cobalt2
code --install-extension wholroyd.jinja
code --install-extension WillLuke.nextjs
code --install-extension willstakayama.vscode-nextjs-snippets
code --install-extension wix.vscode-import-cost
code --install-extension xdebug.php-debug
code --install-extension Zaczero.bootstrap-v4-snippets
