code --install-extension 2gua.rainbow-brackets
code --install-extension ahmadawais.shades-of-purple
code --install-extension akamud.vscode-theme-onedark
code --install-extension alefragnani.numbered-bookmarks
code --install-extension andys8.jest-snippets
code --install-extension BeardedBear.beardedtheme
code --install-extension Blackboxapp.blackbox
code --install-extension cliffordfajardo.highlight-line-vscode
code --install-extension d-koppenhagen.file-tree-to-text-generator
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension denoland.vscode-deno
code --install-extension dracula-theme.theme-dracula
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension EQuimper.react-native-react-redux
code --install-extension esbenp.prettier-vscode
code --install-extension firsttris.vscode-jest-runner
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension fractalbrew.backticks
code --install-extension Harshil-Kaneria.tasklist
code --install-extension infeng.vscode-react-typescript
code --install-extension JackPaget.gruvbox-glass
code --install-extension jasonlhy.hungry-delete
code --install-extension JerryHong.autofilename
code --install-extension johnpapa.Angular2
code --install-extension jundat95.react-native-snippet
code --install-extension kakumei.ts-debug
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension liamhammett.inline-parameters
code --install-extension lllllllqw.jsdoc
code --install-extension marabesi.php-import-checker
code --install-extension Mikael.Angular-BeastCode
code --install-extension moalamri.inline-fold
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension Nash.awesome-flutter-snippets
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel5-snippets
code --install-extension PKief.material-icon-theme
code --install-extension Prisma.prisma
code --install-extension PulkitGangwar.nextjs-snippets
code --install-extension rangav.vscode-thunder-client
code --install-extension ritwickdey.LiveServer
code --install-extension roerohan.mongo-snippets-for-node-js
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension ryannaddy.laravel-artisan
code --install-extension s-nlf-fh.glassit
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension Shinotatwu-DS.file-tree-generator
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension solidjs-community.solid-snippets
code --install-extension steoates.autoimport
code --install-extension tal7aouy.theme
code --install-extension teabyii.ayu
code --install-extension toba.vsfire
code --install-extension vincaslt.highlight-matching-tag
code --install-extension vinliao.fast-arrow
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension WakaTime.vscode-wakatime
code --install-extension wart.ariake-dark
code --install-extension WillLuke.nextjs
code --install-extension willstakayama.vscode-nextjs-snippets
code --install-extension wix.vscode-import-cost
code --install-extension xdebug.php-debug
